# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClothesStore' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClothesStore

  target 'ClothesStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClothesStoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
